name: docker

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "*.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 7.4
          args: --no-interaction --no-suggest --no-dev --ignore-platform-reqs

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push image
        run: |
          ls -al vendor
          docker build -t ghcr.io/${{ github.repository_owner }}/monica -f Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/monica
